# Generated by Django 4.1 on 2022-09-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cabinets',
            fields=[
                ('cabin_number', models.IntegerField(primary_key=True, serialize=False)),
                ('lead_employee', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cabinets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConstructionOperations',
            fields=[
                ('construction_operation_number', models.AutoField(primary_key=True, serialize=False)),
                ('construction_operation_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'construction_operations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConstructionSite',
            fields=[
                ('construction_site_number', models.AutoField(primary_key=True, serialize=False)),
                ('construction_site_name', models.CharField(blank=True, max_length=255, null=True)),
                ('construction_deadline', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'construction_site',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConstructionType',
            fields=[
                ('construction_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('construction_type', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'construction_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'departments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoEvolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=200)),
                ('label', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_evolution',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoProjectVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.TextField()),
                ('when', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_project_version',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeePositions',
            fields=[
                ('employee_posotion_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_position_name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'employee_positions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('t_number', models.AutoField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(blank=True, max_length=45, null=True)),
                ('patronymic', models.CharField(blank=True, max_length=45, null=True)),
                ('l_name', models.CharField(blank=True, max_length=45, null=True)),
                ('work_since', models.DateField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeesCon',
            fields=[
                ('t_number', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=45, null=True)),
                ('f_name', models.CharField(blank=True, max_length=45, null=True)),
                ('patronymic', models.CharField(blank=True, max_length=45, null=True)),
                ('l_name', models.CharField(blank=True, max_length=45, null=True)),
                ('cabin_number', models.IntegerField(blank=True, null=True)),
                ('construction_operation_name', models.CharField(blank=True, max_length=255, null=True)),
                ('work_since', models.DateField(blank=True, null=True)),
                ('lead_employee_value', models.CharField(blank=True, max_length=45, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('employee_position_name', models.CharField(blank=True, max_length=45, null=True)),
                ('department_name', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'employees_con',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LeadEmployee',
            fields=[
                ('lead_employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('lead_employee_value', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'lead_employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('task_number', models.AutoField(primary_key=True, serialize=False)),
                ('task_deadline', models.DateTimeField(blank=True, null=True)),
                ('task_given', models.DateTimeField(blank=True, null=True)),
                ('task_managed', models.DateTimeField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'tasks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Titles',
            fields=[
                ('title_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'titles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebpushGroup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'webpush_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebpushPushinformation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'webpush_pushinformation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebpushSubscriptioninfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('browser', models.CharField(max_length=100)),
                ('endpoint', models.CharField(max_length=500)),
                ('auth', models.CharField(max_length=100)),
                ('p256dh', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'webpush_subscriptioninfo',
                'managed': False,
            },
        ),
    ]
